name: GitHub Actions CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: GitOps Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # values.yamlの更新、新規ブランチ作成、プッシュ、プルリクエスト
      - name: Update values.yaml & Pull Request to Config Repository
        run: |
          # GitHubログイン
          echo -e "machine github.com\nlogin ${{ secrets.GIT_NAME }}\npasswd ${{ secrets.GH_PASSWORD }}" > ~/.netrc
          # 「config」リポジトリからクローン
          git clone https://github.com/${{ secrets.GIT_NAME }}/config.git
          # values.yamlファイルの更新処理
          cd config/gitops-helm
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
          # 新規ブランチ作成
          git branch feature/${{ github.run_number }}
          git checkout feature/${{ github.run_number }}
          # values.yamlのタグ番号を更新
          sed -i 's/tag: [0-9]*/tag: ${{ github.run_number }}/g' values.yaml
          # プッシュ処理1
          git add values.yaml
          git commit -m "Update tag ${{ github.run_number }}"
          git remote rm https://github.com/miyukihub/config.git
          git remote add origin https://miyukihub:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github/config.git
          git remote -v
          git branch
          echo "git push  origin feature/${{ github.run_number }}"
          git push origin feature/${{ github.run_number }}
          ## プルリクエスト処理
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt
          gh pr create  --title "Update Tag ${{ github.run_number }}" --body "Please Merge !!" 
